import { Decision, Incident, SimulatedMessage, Task } from "../types.js";
import { groqComplete } from "../services/groqService.js";

const evidenceRef = (message: SimulatedMessage) => `${message.id} in ${message.channel}`;

function buildFallbackPostmortem(input: {
  incident: Incident;
  messages: SimulatedMessage[];
  tasks: Task[];
  decisions: Decision[];
}): string {
  const first = input.messages.slice().sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts))[0];
  const resolvedTasks = input.tasks.filter((t) => t.status === "resolved").length;
  const openTasks = input.tasks.length - resolvedTasks;
  return [
    `# Postmortem Draft: ${input.incident.title}`,
    "",
    "## Summary",
    `A ${input.incident.severity} incident affected hospital clinic operations during storm response. First sourced signal: ${first?.text ?? "not available"}`,
    "",
    "## Impact",
    "- Patient portal confirmations and support operations were disrupted.",
    "- Clinic B field operations required backup power/resource dispatch.",
    "",
    "## Root Cause Hypothesis",
    "API gateway/DNS instability during failover is the current hypothesis.",
    "",
    "## What Went Well",
    "- CrisisOps consolidated signals across channels.",
    "- Resource matching identified available field assets.",
    "- Decisions and approvals were captured for auditability.",
    "",
    "## What Went Wrong",
    "- Incident commander and customer comms owner were not clear in early messages.",
    "- External vendor confirmation was a blocker.",
    "",
    "## Follow-Up Actions",
    `- ${openTasks} open tasks remain; ${resolvedTasks} tasks resolved.`,
    "- Add explicit owner assignment to incident launch checklist.",
    "- Pre-approve field dispatch thresholds for clinic continuity incidents.",
    "",
    "## Decision Ledger",
    ...(input.decisions.length
      ? input.decisions.map((d) => `- ${d.text} | owner: ${d.owner} | status: ${d.approvalStatus}`)
      : ["- No decisions recorded."]),
    "",
    "## Evidence",
    ...input.messages.slice(0, 8).map((m) => `- ${evidenceRef(m)}: ${m.text}`)
  ].join("\n");
}

export async function generatePostmortem(input: {
  incident: Incident;
  messages: SimulatedMessage[];
  tasks: Task[];
  decisions: Decision[];
}): Promise<string> {
  const resolvedTasks = input.tasks.filter((t) => t.status === "resolved").length;
  const openTasks = input.tasks.length - resolvedTasks;

  const evidenceBlock = input.messages
    .slice()
    .sort((a, b) => Date.parse(a.ts) - Date.parse(b.ts))
    .map((m) => `[${m.channel} / ${m.user}] ${m.text}`)
    .join("\n");

  const decisionBlock = input.decisions.length
    ? input.decisions.map((d) => `- ${d.text} (owner: ${d.owner}, status: ${d.approvalStatus}, risk: ${d.risk})`).join("\n")
    : "None recorded.";

  const taskBlock = input.tasks.length
    ? input.tasks.map((t) => `- [${t.status}] ${t.title}`).join("\n")
    : "None.";

  const systemPrompt = `You are an incident post-incident review AI embedded in Slack.
Write a professional, structured postmortem report based only on the evidence provided.
Rules:
- Only state facts present in the evidence. Never invent details.
- Cite channel/user when referencing evidence.
- Use these sections: Summary, Impact, Timeline, Root Cause Hypothesis, What Went Well, What Went Wrong, Follow-Up Actions, Decision Ledger.
- Be concise and actionable. Under 500 words total.`;

  const userPrompt = `Incident: ${input.incident.title}
Severity: ${input.incident.severity} | Status: ${input.incident.status}
Open tasks: ${openTasks} | Resolved tasks: ${resolvedTasks}

Evidence from Slack (${input.messages.length} messages):
${evidenceBlock}

Decisions made:
${decisionBlock}

Tasks:
${taskBlock}

Write the postmortem now.`;

  const llmContent = await groqComplete(systemPrompt, userPrompt, 700);

  if (llmContent) {
    return `# Postmortem: ${input.incident.title}\n\n${llmContent}\n\n─────────────────────────\n⚡ Generated by Groq LLaMA-3.3-70b · Evidence-grounded`;
  }

  return buildFallbackPostmortem(input);
}
